CREATE DATABASE delivery_food
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

create table if not exists public."users"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) not null,
    surname varchar(200) not null,
    email varchar(200) not null unique,
    photo_link varchar(500),
    password varchar(200) not null
);

create table if not exists public."baskets"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint not null REFERENCES users
);

create table if not exists public."restaurants"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(200) not null unique,
   	description text not null
);

create table if not exists public."admins"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	name varchar(200) not null unique,
	password varchar(200) not null,
	restaurant_id int references restaurants
);

create table if not exists public."favourite_restaurants"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	user_id bigint not null references users,
	restaurant_id int not null references restaurants
);

create table if not exists public."categories"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	category varchar(200) not null
);

create table if not exists public."dishes"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title varchar(500) not null,
	description text not null,
	photo_link varchar(500),
	price money default 0 not null,
   	category_id int references categories,
	restaurant_id int references restaurants
);

create table if not exists public."reviews"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	review text not null,
	restaurant_id int references restaurants
);

create table if not exists public."delivery_addresses"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint references users,
	address_name varchar(200) not null,
	address varchar(400) not null unique
);

create type order_status as enum('new', 'accepted', 'delivers', 'delivered', 'done', 'canceled');

create table if not exists public."orders"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id bigint references users,
	delivery_address_id bigint,
	order_cost money default 0 not null,
	restaurant_id int references restaurants not null,
	order_time timestamptz not null,
	status order_status default 'new' not null
);

create table if not exists public."list_of_dishes_order"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_id bigint references orders not null,
	dish_id bigint references dishes not null,
	quantity smallint default 1 not null
);

create table if not exists public."list_of_dishes_basket"
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	basket_id bigint references baskets not null,
	dish_id bigint references dishes not null
);